package ProtoBufDemo;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataMsg.proto

public final class DataMsg {
  private DataMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 frame = 1;
    /**
     * <code>required int32 frame = 1;</code>
     *
     * <pre>
     * ID���ڼ���������һ֡ͼ�񣨱��裩  
     * </pre>
     */
    boolean hasFrame();
    /**
     * <code>required int32 frame = 1;</code>
     *
     * <pre>
     * ID���ڼ���������һ֡ͼ�񣨱��裩  
     * </pre>
     */
    int getFrame();

    // repeated int32 datas = 2;
    /**
     * <code>repeated int32 datas = 2;</code>
     *
     * <pre>
     * �������ĵ����ݣ����ϣ� 
     * </pre>
     */
    java.util.List<Integer> getDatasList();
    /**
     * <code>repeated int32 datas = 2;</code>
     *
     * <pre>
     * �������ĵ����ݣ����ϣ� 
     * </pre>
     */
    int getDatasCount();
    /**
     * <code>repeated int32 datas = 2;</code>
     *
     * <pre>
     * �������ĵ����ݣ����ϣ� 
     * </pre>
     */
    int getDatas(int index);

    // optional bool isDrawed = 3;
    /**
     * <code>optional bool isDrawed = 3;</code>
     *
     * <pre>
     * �Ƿ�����˵�ǰ֡ͼ�񣨿�ѡ��  
     * </pre>
     */
    boolean hasIsDrawed();
    /**
     * <code>optional bool isDrawed = 3;</code>
     *
     * <pre>
     * �Ƿ�����˵�ǰ֡ͼ�񣨿�ѡ��  
     * </pre>
     */
    boolean getIsDrawed();
  }
  /**
   * Protobuf type {@code Data}
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessage
      implements DataOrBuilder {
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Data(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Data defaultInstance;
    public static Data getDefaultInstance() {
      return defaultInstance;
    }

    public Data getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              frame_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                datas_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              datas_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                datas_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                datas_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              isDrawed_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          datas_ = java.util.Collections.unmodifiableList(datas_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataMsg.internal_static_Data_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataMsg.internal_static_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Data.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Data> PARSER =
        new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 frame = 1;
    public static final int FRAME_FIELD_NUMBER = 1;
    private int frame_;
    /**
     * <code>required int32 frame = 1;</code>
     *
     * <pre>
     * ID���ڼ���������һ֡ͼ�񣨱��裩  
     * </pre>
     */
    public boolean hasFrame() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 frame = 1;</code>
     *
     * <pre>
     * ID���ڼ���������һ֡ͼ�񣨱��裩  
     * </pre>
     */
    public int getFrame() {
      return frame_;
    }

    // repeated int32 datas = 2;
    public static final int DATAS_FIELD_NUMBER = 2;
    private java.util.List<Integer> datas_;
    /**
     * <code>repeated int32 datas = 2;</code>
     *
     * <pre>
     * �������ĵ����ݣ����ϣ� 
     * </pre>
     */
    public java.util.List<Integer>
        getDatasList() {
      return datas_;
    }
    /**
     * <code>repeated int32 datas = 2;</code>
     *
     * <pre>
     * �������ĵ����ݣ����ϣ� 
     * </pre>
     */
    public int getDatasCount() {
      return datas_.size();
    }
    /**
     * <code>repeated int32 datas = 2;</code>
     *
     * <pre>
     * �������ĵ����ݣ����ϣ� 
     * </pre>
     */
    public int getDatas(int index) {
      return datas_.get(index);
    }

    // optional bool isDrawed = 3;
    public static final int ISDRAWED_FIELD_NUMBER = 3;
    private boolean isDrawed_;
    /**
     * <code>optional bool isDrawed = 3;</code>
     *
     * <pre>
     * �Ƿ�����˵�ǰ֡ͼ�񣨿�ѡ��  
     * </pre>
     */
    public boolean hasIsDrawed() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool isDrawed = 3;</code>
     *
     * <pre>
     * �Ƿ�����˵�ǰ֡ͼ�񣨿�ѡ��  
     * </pre>
     */
    public boolean getIsDrawed() {
      return isDrawed_;
    }

    private void initFields() {
      frame_ = 0;
      datas_ = java.util.Collections.emptyList();
      isDrawed_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFrame()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, frame_);
      }
      for (int i = 0; i < datas_.size(); i++) {
        output.writeInt32(2, datas_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(3, isDrawed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, frame_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < datas_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(datas_.get(i));
        }
        size += dataSize;
        size += 1 * getDatasList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isDrawed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Data prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataMsg.internal_static_Data_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataMsg.internal_static_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Data.class, Builder.class);
      }

      // Construct using DataMsg.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        frame_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        datas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        isDrawed_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataMsg.internal_static_Data_descriptor;
      }

      public Data getDefaultInstanceForType() {
        return Data.getDefaultInstance();
      }

      public Data build() {
        Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Data buildPartial() {
        Data result = new Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.frame_ = frame_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          datas_ = java.util.Collections.unmodifiableList(datas_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.datas_ = datas_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isDrawed_ = isDrawed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Data) {
          return mergeFrom((Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Data other) {
        if (other == Data.getDefaultInstance()) return this;
        if (other.hasFrame()) {
          setFrame(other.getFrame());
        }
        if (!other.datas_.isEmpty()) {
          if (datas_.isEmpty()) {
            datas_ = other.datas_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDatasIsMutable();
            datas_.addAll(other.datas_);
          }
          onChanged();
        }
        if (other.hasIsDrawed()) {
          setIsDrawed(other.getIsDrawed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFrame()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Data) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 frame = 1;
      private int frame_ ;
      /**
       * <code>required int32 frame = 1;</code>
       *
       * <pre>
       * ID���ڼ���������һ֡ͼ�񣨱��裩  
       * </pre>
       */
      public boolean hasFrame() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 frame = 1;</code>
       *
       * <pre>
       * ID���ڼ���������һ֡ͼ�񣨱��裩  
       * </pre>
       */
      public int getFrame() {
        return frame_;
      }
      /**
       * <code>required int32 frame = 1;</code>
       *
       * <pre>
       * ID���ڼ���������һ֡ͼ�񣨱��裩  
       * </pre>
       */
      public Builder setFrame(int value) {
        bitField0_ |= 0x00000001;
        frame_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 frame = 1;</code>
       *
       * <pre>
       * ID���ڼ���������һ֡ͼ�񣨱��裩  
       * </pre>
       */
      public Builder clearFrame() {
        bitField0_ = (bitField0_ & ~0x00000001);
        frame_ = 0;
        onChanged();
        return this;
      }

      // repeated int32 datas = 2;
      private java.util.List<Integer> datas_ = java.util.Collections.emptyList();
      private void ensureDatasIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          datas_ = new java.util.ArrayList<Integer>(datas_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 datas = 2;</code>
       *
       * <pre>
       * �������ĵ����ݣ����ϣ� 
       * </pre>
       */
      public java.util.List<Integer>
          getDatasList() {
        return java.util.Collections.unmodifiableList(datas_);
      }
      /**
       * <code>repeated int32 datas = 2;</code>
       *
       * <pre>
       * �������ĵ����ݣ����ϣ� 
       * </pre>
       */
      public int getDatasCount() {
        return datas_.size();
      }
      /**
       * <code>repeated int32 datas = 2;</code>
       *
       * <pre>
       * �������ĵ����ݣ����ϣ� 
       * </pre>
       */
      public int getDatas(int index) {
        return datas_.get(index);
      }
      /**
       * <code>repeated int32 datas = 2;</code>
       *
       * <pre>
       * �������ĵ����ݣ����ϣ� 
       * </pre>
       */
      public Builder setDatas(
          int index, int value) {
        ensureDatasIsMutable();
        datas_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 datas = 2;</code>
       *
       * <pre>
       * �������ĵ����ݣ����ϣ� 
       * </pre>
       */
      public Builder addDatas(int value) {
        ensureDatasIsMutable();
        datas_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 datas = 2;</code>
       *
       * <pre>
       * �������ĵ����ݣ����ϣ� 
       * </pre>
       */
      public Builder addAllDatas(
          Iterable<? extends Integer> values) {
        ensureDatasIsMutable();
        super.addAll(values, datas_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 datas = 2;</code>
       *
       * <pre>
       * �������ĵ����ݣ����ϣ� 
       * </pre>
       */
      public Builder clearDatas() {
        datas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // optional bool isDrawed = 3;
      private boolean isDrawed_ ;
      /**
       * <code>optional bool isDrawed = 3;</code>
       *
       * <pre>
       * �Ƿ�����˵�ǰ֡ͼ�񣨿�ѡ��  
       * </pre>
       */
      public boolean hasIsDrawed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool isDrawed = 3;</code>
       *
       * <pre>
       * �Ƿ�����˵�ǰ֡ͼ�񣨿�ѡ��  
       * </pre>
       */
      public boolean getIsDrawed() {
        return isDrawed_;
      }
      /**
       * <code>optional bool isDrawed = 3;</code>
       *
       * <pre>
       * �Ƿ�����˵�ǰ֡ͼ�񣨿�ѡ��  
       * </pre>
       */
      public Builder setIsDrawed(boolean value) {
        bitField0_ |= 0x00000004;
        isDrawed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isDrawed = 3;</code>
       *
       * <pre>
       * �Ƿ�����˵�ǰ֡ͼ�񣨿�ѡ��  
       * </pre>
       */
      public Builder clearIsDrawed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isDrawed_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Data)
    }

    static {
      defaultInstance = new Data(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Data)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Data_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rDataMsg.proto\"6\n\004Data\022\r\n\005frame\030\001 \002(\005\022\r" +
      "\n\005datas\030\002 \003(\005\022\020\n\010isDrawed\030\003 \001(\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Data_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Data_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Data_descriptor,
              new String[] { "Frame", "Datas", "IsDrawed", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
