package com.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FeedbackInfoFromClienttoServer.proto

public final class FeedbackInfoFromClienttoServer {
  private FeedbackInfoFromClienttoServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FeedbackInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool isDrawed = 1;
    /**
     * <code>required bool isDrawed = 1;</code>
     *
     * <pre>
     * �Ƿ�����˵�ǰ֡ͼ�񣨱��裩  
     * </pre>
     */
    boolean hasIsDrawed();
    /**
     * <code>required bool isDrawed = 1;</code>
     *
     * <pre>
     * �Ƿ�����˵�ǰ֡ͼ�񣨱��裩  
     * </pre>
     */
    boolean getIsDrawed();

    // required int32 lastframeC = 2;
    /**
     * <code>required int32 lastframeC = 2;</code>
     *
     * <pre>
     * ǰһ֡ͼ����������裩  
     * </pre>
     */
    boolean hasLastframeC();
    /**
     * <code>required int32 lastframeC = 2;</code>
     *
     * <pre>
     * ǰһ֡ͼ����������裩  
     * </pre>
     */
    int getLastframeC();

    // required int32 currentframeC = 3;
    /**
     * <code>required int32 currentframeC = 3;</code>
     *
     * <pre>
     * ��ǰ֡ͼ����������裩  
     * </pre>
     */
    boolean hasCurrentframeC();
    /**
     * <code>required int32 currentframeC = 3;</code>
     *
     * <pre>
     * ��ǰ֡ͼ����������裩  
     * </pre>
     */
    int getCurrentframeC();
  }
  /**
   * Protobuf type {@code FeedbackInfo}
   */
  public static final class FeedbackInfo extends
      com.google.protobuf.GeneratedMessage
      implements FeedbackInfoOrBuilder {
    // Use FeedbackInfo.newBuilder() to construct.
    private FeedbackInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FeedbackInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FeedbackInfo defaultInstance;
    public static FeedbackInfo getDefaultInstance() {
      return defaultInstance;
    }

    public FeedbackInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FeedbackInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isDrawed_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lastframeC_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              currentframeC_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FeedbackInfoFromClienttoServer.internal_static_FeedbackInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FeedbackInfoFromClienttoServer.internal_static_FeedbackInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FeedbackInfo.class, Builder.class);
    }

    public static com.google.protobuf.Parser<FeedbackInfo> PARSER =
        new com.google.protobuf.AbstractParser<FeedbackInfo>() {
      public FeedbackInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeedbackInfo(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<FeedbackInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool isDrawed = 1;
    public static final int ISDRAWED_FIELD_NUMBER = 1;
    private boolean isDrawed_;
    /**
     * <code>required bool isDrawed = 1;</code>
     *
     * <pre>
     * �Ƿ�����˵�ǰ֡ͼ�񣨱��裩  
     * </pre>
     */
    public boolean hasIsDrawed() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool isDrawed = 1;</code>
     *
     * <pre>
     * �Ƿ�����˵�ǰ֡ͼ�񣨱��裩  
     * </pre>
     */
    public boolean getIsDrawed() {
      return isDrawed_;
    }

    // required int32 lastframeC = 2;
    public static final int LASTFRAMEC_FIELD_NUMBER = 2;
    private int lastframeC_;
    /**
     * <code>required int32 lastframeC = 2;</code>
     *
     * <pre>
     * ǰһ֡ͼ����������裩  
     * </pre>
     */
    public boolean hasLastframeC() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 lastframeC = 2;</code>
     *
     * <pre>
     * ǰһ֡ͼ����������裩  
     * </pre>
     */
    public int getLastframeC() {
      return lastframeC_;
    }

    // required int32 currentframeC = 3;
    public static final int CURRENTFRAMEC_FIELD_NUMBER = 3;
    private int currentframeC_;
    /**
     * <code>required int32 currentframeC = 3;</code>
     *
     * <pre>
     * ��ǰ֡ͼ����������裩  
     * </pre>
     */
    public boolean hasCurrentframeC() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 currentframeC = 3;</code>
     *
     * <pre>
     * ��ǰ֡ͼ����������裩  
     * </pre>
     */
    public int getCurrentframeC() {
      return currentframeC_;
    }

    private void initFields() {
      isDrawed_ = false;
      lastframeC_ = 0;
      currentframeC_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIsDrawed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastframeC()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurrentframeC()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isDrawed_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, lastframeC_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, currentframeC_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isDrawed_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lastframeC_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, currentframeC_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static FeedbackInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FeedbackInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FeedbackInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FeedbackInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FeedbackInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static FeedbackInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static FeedbackInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static FeedbackInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static FeedbackInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static FeedbackInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(FeedbackInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FeedbackInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements FeedbackInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FeedbackInfoFromClienttoServer.internal_static_FeedbackInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FeedbackInfoFromClienttoServer.internal_static_FeedbackInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FeedbackInfo.class, Builder.class);
      }

      // Construct using FeedbackInfoFromClienttoServer.FeedbackInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isDrawed_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        lastframeC_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        currentframeC_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FeedbackInfoFromClienttoServer.internal_static_FeedbackInfo_descriptor;
      }

      public FeedbackInfo getDefaultInstanceForType() {
        return FeedbackInfo.getDefaultInstance();
      }

      public FeedbackInfo build() {
        FeedbackInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public FeedbackInfo buildPartial() {
        FeedbackInfo result = new FeedbackInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isDrawed_ = isDrawed_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lastframeC_ = lastframeC_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.currentframeC_ = currentframeC_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FeedbackInfo) {
          return mergeFrom((FeedbackInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FeedbackInfo other) {
        if (other == FeedbackInfo.getDefaultInstance()) return this;
        if (other.hasIsDrawed()) {
          setIsDrawed(other.getIsDrawed());
        }
        if (other.hasLastframeC()) {
          setLastframeC(other.getLastframeC());
        }
        if (other.hasCurrentframeC()) {
          setCurrentframeC(other.getCurrentframeC());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsDrawed()) {
          
          return false;
        }
        if (!hasLastframeC()) {
          
          return false;
        }
        if (!hasCurrentframeC()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FeedbackInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FeedbackInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool isDrawed = 1;
      private boolean isDrawed_ ;
      /**
       * <code>required bool isDrawed = 1;</code>
       *
       * <pre>
       * �Ƿ�����˵�ǰ֡ͼ�񣨱��裩  
       * </pre>
       */
      public boolean hasIsDrawed() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool isDrawed = 1;</code>
       *
       * <pre>
       * �Ƿ�����˵�ǰ֡ͼ�񣨱��裩  
       * </pre>
       */
      public boolean getIsDrawed() {
        return isDrawed_;
      }
      /**
       * <code>required bool isDrawed = 1;</code>
       *
       * <pre>
       * �Ƿ�����˵�ǰ֡ͼ�񣨱��裩  
       * </pre>
       */
      public Builder setIsDrawed(boolean value) {
        bitField0_ |= 0x00000001;
        isDrawed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isDrawed = 1;</code>
       *
       * <pre>
       * �Ƿ�����˵�ǰ֡ͼ�񣨱��裩  
       * </pre>
       */
      public Builder clearIsDrawed() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isDrawed_ = false;
        onChanged();
        return this;
      }

      // required int32 lastframeC = 2;
      private int lastframeC_ ;
      /**
       * <code>required int32 lastframeC = 2;</code>
       *
       * <pre>
       * ǰһ֡ͼ����������裩  
       * </pre>
       */
      public boolean hasLastframeC() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 lastframeC = 2;</code>
       *
       * <pre>
       * ǰһ֡ͼ����������裩  
       * </pre>
       */
      public int getLastframeC() {
        return lastframeC_;
      }
      /**
       * <code>required int32 lastframeC = 2;</code>
       *
       * <pre>
       * ǰһ֡ͼ����������裩  
       * </pre>
       */
      public Builder setLastframeC(int value) {
        bitField0_ |= 0x00000002;
        lastframeC_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 lastframeC = 2;</code>
       *
       * <pre>
       * ǰһ֡ͼ����������裩  
       * </pre>
       */
      public Builder clearLastframeC() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastframeC_ = 0;
        onChanged();
        return this;
      }

      // required int32 currentframeC = 3;
      private int currentframeC_ ;
      /**
       * <code>required int32 currentframeC = 3;</code>
       *
       * <pre>
       * ��ǰ֡ͼ����������裩  
       * </pre>
       */
      public boolean hasCurrentframeC() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 currentframeC = 3;</code>
       *
       * <pre>
       * ��ǰ֡ͼ����������裩  
       * </pre>
       */
      public int getCurrentframeC() {
        return currentframeC_;
      }
      /**
       * <code>required int32 currentframeC = 3;</code>
       *
       * <pre>
       * ��ǰ֡ͼ����������裩  
       * </pre>
       */
      public Builder setCurrentframeC(int value) {
        bitField0_ |= 0x00000004;
        currentframeC_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 currentframeC = 3;</code>
       *
       * <pre>
       * ��ǰ֡ͼ����������裩  
       * </pre>
       */
      public Builder clearCurrentframeC() {
        bitField0_ = (bitField0_ & ~0x00000004);
        currentframeC_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FeedbackInfo)
    }

    static {
      defaultInstance = new FeedbackInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FeedbackInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FeedbackInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FeedbackInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n$FeedbackInfoFromClienttoServer.proto\"K" +
      "\n\014FeedbackInfo\022\020\n\010isDrawed\030\001 \002(\010\022\022\n\nlast" +
      "frameC\030\002 \002(\005\022\025\n\rcurrentframeC\030\003 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_FeedbackInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_FeedbackInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FeedbackInfo_descriptor,
              new String[] { "IsDrawed", "LastframeC", "CurrentframeC", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
