package com.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InfoConfirm.proto

public final class InfoConfirm {
  private InfoConfirm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ComfirmInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool androidFrame = 1;
    /**
     * <code>required bool androidFrame = 1;</code>
     *
     * <pre>
     * ��׿����֡ͼ�񣨱��裩  
     * </pre>
     */
    boolean hasAndroidFrame();
    /**
     * <code>required bool androidFrame = 1;</code>
     *
     * <pre>
     * ��׿����֡ͼ�񣨱��裩  
     * </pre>
     */
    boolean getAndroidFrame();
  }
  /**
   * Protobuf type {@code ComfirmInfo}
   */
  public static final class ComfirmInfo extends
      com.google.protobuf.GeneratedMessage
      implements ComfirmInfoOrBuilder {
    // Use ComfirmInfo.newBuilder() to construct.
    private ComfirmInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ComfirmInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ComfirmInfo defaultInstance;
    public static ComfirmInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ComfirmInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ComfirmInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              androidFrame_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return InfoConfirm.internal_static_ComfirmInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return InfoConfirm.internal_static_ComfirmInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ComfirmInfo.class, Builder.class);
    }

    public static com.google.protobuf.Parser<ComfirmInfo> PARSER =
        new com.google.protobuf.AbstractParser<ComfirmInfo>() {
      public ComfirmInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ComfirmInfo(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<ComfirmInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool androidFrame = 1;
    public static final int ANDROIDFRAME_FIELD_NUMBER = 1;
    private boolean androidFrame_;
    /**
     * <code>required bool androidFrame = 1;</code>
     *
     * <pre>
     * ��׿����֡ͼ�񣨱��裩  
     * </pre>
     */
    public boolean hasAndroidFrame() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool androidFrame = 1;</code>
     *
     * <pre>
     * ��׿����֡ͼ�񣨱��裩  
     * </pre>
     */
    public boolean getAndroidFrame() {
      return androidFrame_;
    }

    private void initFields() {
      androidFrame_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAndroidFrame()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, androidFrame_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, androidFrame_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ComfirmInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComfirmInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComfirmInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComfirmInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComfirmInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ComfirmInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ComfirmInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ComfirmInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ComfirmInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ComfirmInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ComfirmInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ComfirmInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ComfirmInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return InfoConfirm.internal_static_ComfirmInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return InfoConfirm.internal_static_ComfirmInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ComfirmInfo.class, Builder.class);
      }

      // Construct using InfoConfirm.ComfirmInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        androidFrame_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return InfoConfirm.internal_static_ComfirmInfo_descriptor;
      }

      public ComfirmInfo getDefaultInstanceForType() {
        return ComfirmInfo.getDefaultInstance();
      }

      public ComfirmInfo build() {
        ComfirmInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ComfirmInfo buildPartial() {
        ComfirmInfo result = new ComfirmInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.androidFrame_ = androidFrame_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ComfirmInfo) {
          return mergeFrom((ComfirmInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ComfirmInfo other) {
        if (other == ComfirmInfo.getDefaultInstance()) return this;
        if (other.hasAndroidFrame()) {
          setAndroidFrame(other.getAndroidFrame());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAndroidFrame()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ComfirmInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ComfirmInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool androidFrame = 1;
      private boolean androidFrame_ ;
      /**
       * <code>required bool androidFrame = 1;</code>
       *
       * <pre>
       * ��׿����֡ͼ�񣨱��裩  
       * </pre>
       */
      public boolean hasAndroidFrame() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool androidFrame = 1;</code>
       *
       * <pre>
       * ��׿����֡ͼ�񣨱��裩  
       * </pre>
       */
      public boolean getAndroidFrame() {
        return androidFrame_;
      }
      /**
       * <code>required bool androidFrame = 1;</code>
       *
       * <pre>
       * ��׿����֡ͼ�񣨱��裩  
       * </pre>
       */
      public Builder setAndroidFrame(boolean value) {
        bitField0_ |= 0x00000001;
        androidFrame_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool androidFrame = 1;</code>
       *
       * <pre>
       * ��׿����֡ͼ�񣨱��裩  
       * </pre>
       */
      public Builder clearAndroidFrame() {
        bitField0_ = (bitField0_ & ~0x00000001);
        androidFrame_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ComfirmInfo)
    }

    static {
      defaultInstance = new ComfirmInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ComfirmInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ComfirmInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ComfirmInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021InfoConfirm.proto\"#\n\013ComfirmInfo\022\024\n\014an" +
      "droidFrame\030\001 \002(\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ComfirmInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ComfirmInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ComfirmInfo_descriptor,
              new String[] { "AndroidFrame", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
