package com.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InitialDataFromClienttoServer.proto

public final class InitialDataFromClienttoServer {
  private InitialDataFromClienttoServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InitialDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string username = 1;
    /**
     * <code>required string username = 1;</code>
     *
     * <pre>
     * �û��������裩  
     * </pre>
     */
    boolean hasUsername();
    /**
     * <code>required string username = 1;</code>
     *
     * <pre>
     * �û��������裩  
     * </pre>
     */
    String getUsername();
    /**
     * <code>required string username = 1;</code>
     *
     * <pre>
     * �û��������裩  
     * </pre>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    // required string password = 2;
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     * ���루���裩  
     * </pre>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     * ���루���裩  
     * </pre>
     */
    String getPassword();
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     * ���루���裩  
     * </pre>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    // repeated int32 initialDatas = 3;
    /**
     * <code>repeated int32 initialDatas = 3;</code>
     *
     * <pre>
     * ѹ�����ĵ����ݣ����ϣ�  
     * </pre>
     */
    java.util.List<Integer> getInitialDatasList();
    /**
     * <code>repeated int32 initialDatas = 3;</code>
     *
     * <pre>
     * ѹ�����ĵ����ݣ����ϣ�  
     * </pre>
     */
    int getInitialDatasCount();
    /**
     * <code>repeated int32 initialDatas = 3;</code>
     *
     * <pre>
     * ѹ�����ĵ����ݣ����ϣ�  
     * </pre>
     */
    int getInitialDatas(int index);
  }
  /**
   * Protobuf type {@code InitialData}
   */
  public static final class InitialData extends
      com.google.protobuf.GeneratedMessage
      implements InitialDataOrBuilder {
    // Use InitialData.newBuilder() to construct.
    private InitialData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InitialData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InitialData defaultInstance;
    public static InitialData getDefaultInstance() {
      return defaultInstance;
    }

    public InitialData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InitialData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              username_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                initialDatas_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              initialDatas_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                initialDatas_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                initialDatas_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          initialDatas_ = java.util.Collections.unmodifiableList(initialDatas_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return InitialDataFromClienttoServer.internal_static_InitialData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return InitialDataFromClienttoServer.internal_static_InitialData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InitialData.class, Builder.class);
    }

    public static com.google.protobuf.Parser<InitialData> PARSER =
        new com.google.protobuf.AbstractParser<InitialData>() {
      public InitialData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InitialData(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<InitialData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private Object username_;
    /**
     * <code>required string username = 1;</code>
     *
     * <pre>
     * �û��������裩  
     * </pre>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string username = 1;</code>
     *
     * <pre>
     * �û��������裩  
     * </pre>
     */
    public String getUsername() {
      Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string username = 1;</code>
     *
     * <pre>
     * �û��������裩  
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private Object password_;
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     * ���루���裩  
     * </pre>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     * ���루���裩  
     * </pre>
     */
    public String getPassword() {
      Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     * ���루���裩  
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated int32 initialDatas = 3;
    public static final int INITIALDATAS_FIELD_NUMBER = 3;
    private java.util.List<Integer> initialDatas_;
    /**
     * <code>repeated int32 initialDatas = 3;</code>
     *
     * <pre>
     * ѹ�����ĵ����ݣ����ϣ�  
     * </pre>
     */
    public java.util.List<Integer>
        getInitialDatasList() {
      return initialDatas_;
    }
    /**
     * <code>repeated int32 initialDatas = 3;</code>
     *
     * <pre>
     * ѹ�����ĵ����ݣ����ϣ�  
     * </pre>
     */
    public int getInitialDatasCount() {
      return initialDatas_.size();
    }
    /**
     * <code>repeated int32 initialDatas = 3;</code>
     *
     * <pre>
     * ѹ�����ĵ����ݣ����ϣ�  
     * </pre>
     */
    public int getInitialDatas(int index) {
      return initialDatas_.get(index);
    }

    private void initFields() {
      username_ = "";
      password_ = "";
      initialDatas_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      for (int i = 0; i < initialDatas_.size(); i++) {
        output.writeInt32(3, initialDatas_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < initialDatas_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(initialDatas_.get(i));
        }
        size += dataSize;
        size += 1 * getInitialDatasList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static InitialData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InitialData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InitialData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InitialData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InitialData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static InitialData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static InitialData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static InitialData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static InitialData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static InitialData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(InitialData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InitialData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements InitialDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return InitialDataFromClienttoServer.internal_static_InitialData_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return InitialDataFromClienttoServer.internal_static_InitialData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                InitialData.class, Builder.class);
      }

      // Construct using InitialDataFromClienttoServer.InitialData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        initialDatas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return InitialDataFromClienttoServer.internal_static_InitialData_descriptor;
      }

      public InitialData getDefaultInstanceForType() {
        return InitialData.getDefaultInstance();
      }

      public InitialData build() {
        InitialData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public InitialData buildPartial() {
        InitialData result = new InitialData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          initialDatas_ = java.util.Collections.unmodifiableList(initialDatas_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.initialDatas_ = initialDatas_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof InitialData) {
          return mergeFrom((InitialData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(InitialData other) {
        if (other == InitialData.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          bitField0_ |= 0x00000001;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        if (!other.initialDatas_.isEmpty()) {
          if (initialDatas_.isEmpty()) {
            initialDatas_ = other.initialDatas_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureInitialDatasIsMutable();
            initialDatas_.addAll(other.initialDatas_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        InitialData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (InitialData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string username = 1;
      private Object username_ = "";
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       * �û��������裩  
       * </pre>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       * �û��������裩  
       * </pre>
       */
      public String getUsername() {
        Object ref = username_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       * �û��������裩  
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       * �û��������裩  
       * </pre>
       */
      public Builder setUsername(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       * �û��������裩  
       * </pre>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       * �û��������裩  
       * </pre>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }

      // required string password = 2;
      private Object password_ = "";
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       * ���루���裩  
       * </pre>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       * ���루���裩  
       * </pre>
       */
      public String getPassword() {
        Object ref = password_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       * ���루���裩  
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       * ���루���裩  
       * </pre>
       */
      public Builder setPassword(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       * ���루���裩  
       * </pre>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       * ���루���裩  
       * </pre>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // repeated int32 initialDatas = 3;
      private java.util.List<Integer> initialDatas_ = java.util.Collections.emptyList();
      private void ensureInitialDatasIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          initialDatas_ = new java.util.ArrayList<Integer>(initialDatas_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 initialDatas = 3;</code>
       *
       * <pre>
       * ѹ�����ĵ����ݣ����ϣ�  
       * </pre>
       */
      public java.util.List<Integer>
          getInitialDatasList() {
        return java.util.Collections.unmodifiableList(initialDatas_);
      }
      /**
       * <code>repeated int32 initialDatas = 3;</code>
       *
       * <pre>
       * ѹ�����ĵ����ݣ����ϣ�  
       * </pre>
       */
      public int getInitialDatasCount() {
        return initialDatas_.size();
      }
      /**
       * <code>repeated int32 initialDatas = 3;</code>
       *
       * <pre>
       * ѹ�����ĵ����ݣ����ϣ�  
       * </pre>
       */
      public int getInitialDatas(int index) {
        return initialDatas_.get(index);
      }
      /**
       * <code>repeated int32 initialDatas = 3;</code>
       *
       * <pre>
       * ѹ�����ĵ����ݣ����ϣ�  
       * </pre>
       */
      public Builder setInitialDatas(
          int index, int value) {
        ensureInitialDatasIsMutable();
        initialDatas_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 initialDatas = 3;</code>
       *
       * <pre>
       * ѹ�����ĵ����ݣ����ϣ�  
       * </pre>
       */
      public Builder addInitialDatas(int value) {
        ensureInitialDatasIsMutable();
        initialDatas_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 initialDatas = 3;</code>
       *
       * <pre>
       * ѹ�����ĵ����ݣ����ϣ�  
       * </pre>
       */
      public Builder addAllInitialDatas(
          Iterable<? extends Integer> values) {
        ensureInitialDatasIsMutable();
        super.addAll(values, initialDatas_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 initialDatas = 3;</code>
       *
       * <pre>
       * ѹ�����ĵ����ݣ����ϣ�  
       * </pre>
       */
      public Builder clearInitialDatas() {
        initialDatas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:InitialData)
    }

    static {
      defaultInstance = new InitialData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:InitialData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_InitialData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InitialData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n#InitialDataFromClienttoServer.proto\"G\n" +
      "\013InitialData\022\020\n\010username\030\001 \002(\t\022\020\n\010passwo" +
      "rd\030\002 \002(\t\022\024\n\014initialDatas\030\003 \003(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_InitialData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_InitialData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_InitialData_descriptor,
              new String[] { "Username", "Password", "InitialDatas", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
